### ISSUE TITLE
Slightly unsafe log window update from another thread during startup

### ISSUE THREAD

**Issue by EQAditu** [OverlayPlugin/OverlayPlugin#254]
WinForms is extremely picky about thread safety and UI controls and will throw exceptions when unnecessary.  ACT by default has this checking turned off, but when I'm running my debugging builds, I leave it on to just keep me honest.  

I'm uncertain when this started, but the startup process of the plugin now does one such illegal cross-thread call:
```
{...}
[10/14/2023 10:02:17 PM] Info: AssemblyResolver: Loaded: Fleck, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
[10/14/2023 10:02:17 PM] Info: InitPlugin: Initialised.
[10/14/2023 10:02:22 PM] Error: InitPlugin: System.InvalidOperationException: Cross-thread operation not valid: Control 'logBox' accessed from a thread other than the thread it was created on.
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.TextBoxBase.get_TextLength()
   at RainbowMage.OverlayPlugin.ControlPanel.AddLogEntry(LogEntry entry)
   at RainbowMage.OverlayPlugin.Logger.Log(LogLevel level, String message)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RainbowMage.OverlayPlugin.PluginMain.<<InitPlugin>b__26_3>d.MoveNext()
```

If it's complaining about just reading a property or something else minor, I'll just not even care... but in this case, it is trying to add text to the control from a Task(thread), which is actually unsafe and could potentially "crash" the control unexpectedly.

Adding text(or any real update) should be wrapped with `ActGlobals.oFormActMain.Invoke()`, if not on the UI thread already(`ActGlobals.oFormActMain.InvokeRequired`).  There are lots of ways the code could look.

**Comment by EQAditu** [comment]
The stacktrace is seemingly complaining about this line, which is untouched by your changes:
https://github.com/valarnin/OverlayPlugin/blob/00d8b1221ed4b0e2ec7fbe6c54a7977ceb788a23/OverlayPlugin.Core/Controls/ControlPanel.cs#L115

I'm less worried about there being a problem with reading the `.TextLength` property... but if that line evaluates to true, it will end up assigning to the `.Text` property which is actually a problem.

I don't have plans to re-enable cross-thread checking in ACT... but if any random plugin decides to "do the right thing" and enable it...  OverlayPlugin may no longer start.

**Comment by valarnin** [comment]
I don't know how I missed that assignment 🙃
